feat: xblock skill verification event
open-craft/openedx-events pull request #1
Opened 2022-11-28 07:10 UTC by navinkarkera

Adds data class and event to send skill verification data for an XBlock.

Adds support for array type in avro serialization & de serialization.

**Description:** The idea is that users will verify the tags/skills associated to an XBlock. We want to send this data via openedx-event signals to course-discovery and update the relevant tables.

**JIRA:** `Private-ref`: [BB-6885](https://tasks.opencraft.com/browse/BB-6885)

**Dependencies:** https://github.com/openedx/openedx-events/pull/143 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [x] Version bumped
- [x] Changelog record added
- [x] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2022-12-02 08:10 UTC, tecoholic requested changes
@navinkarkera Nice work here. I think you are a master of iterative development. :) 
I have left a couple suggestions and a question linked to the location of the events in https://github.com/openedx/edx-platform/pull/31350. I will add the +1 once they are resolved.

2022-12-02 08:10 UTC, tecoholic commented on openedx_events/event_bus/avro/custom_serializers.py
> +DEFAULT_CUSTOM_SERIALIZERS = [CourseKeyAvroSerializer, DatetimeAvroSerializer, UsageKeyAvroSerializer]
Nice :)

2022-12-02 08:10 UTC, tecoholic commented on openedx_events/learning/signals.py
> +# .. event_description: Fired when an XBlock skill is verified in LMS.
```suggestion
# .. event_description: Fired when an XBlock skill is verified.
```
Let us keep this generic so that we can use send this event from other places if required.

2022-12-05 13:58 UTC, navinkarkera commented on openedx_events/content_authoring/signals.py
> +# .. event_description: Fired when an XBlock is deleted in Studio.
Resolved in upstream branch i.e. [navin/skill-tagging-events](https://github.com/open-craft/openedx-events/tree/navin/skill-tagging-events)

2022-12-05 13:59 UTC, navinkarkera commented on openedx_events/event_bus/avro/custom_serializers.py
> +DEFAULT_CUSTOM_SERIALIZERS = [CourseKeyAvroSerializer, DatetimeAvroSerializer, UsageKeyAvroSerializer]
This is also part of the upstream branch. :smile: Sorry for the confusion caused by not rebasing after updating it.

2022-12-05 14:00 UTC, navinkarkera commented
@tecoholic Thanks! Addressed all your comments.

2022-12-12 13:41 UTC, tecoholic approved these changes
@navinkarkera :+1: The PR looks good. I think you have missed updating the version for the package.

- [x] I tested this: Relied on the unittests for the serializer as there are no testing instructions. 
- [x] I read through the code
- [ ] I checked for accessibility issues - NA
- [x] Includes documentation

2023-01-04 16:55 UTC, navinkarkera commented
Replaced by https://github.com/openedx/openedx-events/pull/165

2023-01-04 16:55 UTC, closed without merging